server:
  port: 8089
  servlet:
    context-path:
spring:
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/jdyw2_xz?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  freemarker:
    template-loader-path: classpath:/templates
    cache: false
    charset: utf-8
    content-type: text/html
    suffix: .ftl
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: request
mybatis:
  type-aliases-package: com.hndfsj.springboot
mapper:
  mappers:
    - com.hndfsj.springboot.framework.base.BaseMapper
  not-empty: false
  identity: MYSQL

pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
logging:
  config: classpath:log4j2.yml